temp/unpackaged/objects/State_Capital__c.object
<CustomObject>
    <fields>
        <fullName>Capital__c</fullName>
        <label>Capital</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>TextArea</type>
    </fields>
    <label>State&amp;Capital</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>State&amp;Capital Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State&amp;Capital</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MapExample.cls
public class MapExample {
    
    public static void map1(){
        Map<string,string> StateCapitalMap = new Map<string,string>{'Jharkhand' => 'Ranchi','West Bengal' => 'kolkata'};
            }
    
    public static void map2(){
        Map<String,String> StateCapitalMap2 = new Map<String,String>();
        StateCapitalMap2.put('Bihar','Patna');
        StateCapitalMap2.put('Karnataka','Bangalore');
    }
    
    public static void map3(){
        Map<String,String>  StateCapitalMap3 = new Map<String,String>();
        List<State_Capital__c> StateCapitalList = new List<State_Capital__c>();
        StateCapitalList =[select id,State__c,Capital__c from State_Capital__c ];
        System.debug('StateCapitalList');
        for (State_Capital__c   eachRecord : StateCapitalList){
        StateCapitalMap3.put(eachRecord.State__c,eachRecord.Capital__c);
        System.debug('StateCapitalMap3'+StateCapitalMap3);
        }
    }
    public static void map4(){
        Map<Id,String>  StateCapitalMap4 = new Map<Id,String>();
        List<Account> StateCapitalList4 = new List<Account>();
        StateCapitalList4 =[select id,Name,Phone from Account ];
        for (Account   eachRecord : StateCapitalList4){
        StateCapitalMap4.put(eachRecord.id,eachRecord.Phone);
            System.debug('StateCapitalMap4'+StateCapitalMap4);
        }
}
}